--CREATE DATABASE base_test;


--1 EXECUTE this script

--2 Execute the script config_schema_taxonomy to set function

--3 execute such code
/*
 INSERT INTO taxonomy.taxa_nameset
				("name", category, id_taxonref)
				SELECT * FROM taxonomy.pn_taxa_refresh_nameset();
*/

--CREATE SCHEMA taxonomy AUTHORIZATION postgres;
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS postgis_raster;

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS fuzzystrmatch;


CREATE SCHEMA IF NOT EXISTS taxonomy AUTHORIZATION postgres;
GRANT ALL ON SCHEMA taxonomy TO postgres;

CREATE TABLE IF NOT EXISTS taxonomy.taxa_reference (
	id_taxonref int4 NOT NULL,
	basename text NOT NULL,
	authors text NULL,
	id_rank int4 NOT NULL,
	id_parent int4 NULL,
	metadata jsonb NULL,
	properties jsonb NULL,
	published bool NULL,
	accepted bool DEFAULT true NULL
);
-----------------
CREATE TABLE IF NOT EXISTS taxonomy.taxa_nameset (
	"name" text NOT NULL,
	category int4 DEFAULT 5 NULL,
	id_taxonref int4 NULL
);

-----------------
CREATE TABLE IF NOT EXISTS taxonomy.taxa_rank (
	id_rank int4 NOT NULL,
	rank_name text NOT NULL,
	id_rankparent int4 NULL,
	suffix text NULL,
	prefix text NULL
);
-----------------
CREATE TABLE IF NOT EXISTS taxonomy.taxa_wfo (
	basename text NULL,
	authors text NULL,
	id_rank int4 NULL,
	major_plant_group text NULL,
	clade_apg text NULL,
	parent text NULL
);


--add comments
	COMMENT ON COLUMN taxonomy.taxa_rank.id_rank IS 'Unique identifier for the rank';
	COMMENT ON COLUMN taxonomy.taxa_rank.rank_name IS 'The accepted name for the rank';
	COMMENT ON COLUMN taxonomy.taxa_rank.id_rankparent IS 'The lower id_rank authorized as a parent';
	COMMENT ON COLUMN taxonomy.taxa_rank.prefix IS 'The accepted prefix for the rank (e.g., a variety must be preceded by var.)';
	COMMENT ON COLUMN taxonomy.taxa_rank.suffix IS 'The accepted termination for the name of a rank (e.g., a family must end in aceae)';
	COMMENT ON COLUMN taxonomy.taxa_reference.id_taxonref IS 'Unique id for taxon';
	COMMENT ON COLUMN taxonomy.taxa_reference.basename IS 'The basic name of the taxon, excluding any combination';
	COMMENT ON COLUMN taxonomy.taxa_reference.authors IS 'The name of the authors who published the taxon';
	COMMENT ON COLUMN taxonomy.taxa_reference.id_rank IS 'The taxonomic rank of the taxon';
	COMMENT ON COLUMN taxonomy.taxa_reference.id_parent IS 'The hierarchical parent of the taxon';
	COMMENT ON COLUMN taxonomy.taxa_reference.metadata IS 'Metadata of taxonomic repositories';
	COMMENT ON COLUMN taxonomy.taxa_reference.properties IS 'Properties of taxa';
	COMMENT ON COLUMN taxonomy.taxa_reference.published IS 'Is the taxa is already published ?';
	COMMENT ON COLUMN taxonomy.taxa_reference.accepted IS 'Is the taxa is accepted ?';
	COMMENT ON COLUMN taxonomy.taxa_nameset.name IS 'Name of the synonym';
	COMMENT ON COLUMN taxonomy.taxa_nameset.category IS 'Category of synonym, code _category range [0-9]';
	COMMENT ON COLUMN taxonomy.taxa_nameset.id_taxonref IS 'id_taxonref into the taxa_reference table';

--insert data
--taxa_rank
INSERT INTO taxonomy.taxa_rank (id_rank, rank_name, id_rankparent, suffix, prefix)
VALUES
	(1, 'Regnum', NULL, NULL, NULL),
	(2, 'Subregnum', 1, NULL, NULL),
	(3, 'Division', 1, 'phyta', NULL),
	(4, 'Subdivision', 3, 'phytina', NULL),
	(5, 'Supraclassis', 3, 'ae', NULL),
	(6, 'Classis', 3, 'opsida', 'cl.'),
	(7, 'Subclassis', 6, 'idae', 'subcl.'),
	(8, 'Order', 6, 'ales', 'ord.'),
	(9, 'Suborder', 8, 'ineae', 'subord.'),
	(10, 'Family', 8, 'aceae', 'fam.'),
	(11, 'Subfamily', 10, 'oideae', 'subfam.'),
	(12, 'Tribu', 10, 'eae', 'tr.'),
	(13, 'Subtribus', 12, 'inae', 'subtr.'),
	(14, 'Genus', 10, NULL, 'gen.'),
	(15, 'Subgenus', 14, NULL, 'subg.'),
	(16, 'Section', 14, NULL, 'sect.'),
	(17, 'Subsection', 16, NULL, 'subsect.'),
	(18, 'Series', 14, NULL, 'ser.'),
	(19, 'Subseries', 18, NULL, 'subser.'),
	(20, 'Grex specierum', NULL, NULL, ''),
	(21, 'Species', 14, NULL, NULL),
	(22, 'Subspecies', 21, NULL, 'subsp.'),
	(23, 'Variety', 21, NULL, 'var.'),
	(24, 'Subvariety', 23, NULL, 'subvar.'),
	(25, 'Forma', 21, NULL, 'f.'),
	(26, 'Subforma', 25, NULL, 'subf.'),
	(27, 'Lusus', 21, NULL, NULL),
	(28, 'Cultivar', 21, NULL, 'cv.'),
	(29, 'Unknown', NULL, NULL, NULL),
	(30, 'Species temp', NULL, NULL, NULL),
	(31, 'Hybrid', 14, NULL, 'x')
	;
--taxa_wfo
INSERT INTO taxonomy.taxa_wfo (basename, authors, id_rank, major_plant_group, clade_apg, parent)
VALUES
	('acanthaceae', 'Juss.', 10, NULL, NULL, 'lamiales'),
	('achariaceae', 'Harms', 10, NULL, NULL, 'malpighiales'),
	('achatocarpaceae', 'Heimerl', 10, NULL, NULL, 'caryophyllales'),
	('acoraceae', 'Martinov', 10, NULL, NULL, 'acorales'),
	('acorales', 'Mart.', 8, 'Angiosperms', 'Monocots', 'magnoliidae'),
	('acrobolbaceae', 'E.A.Hodgs.', 10, NULL, NULL, 'jungermanniales'),
	('acrocladiaceae', 'Tangney, D.Quandt, Huttunen & M.Stech', 10, NULL, NULL, 'hypnales'),
	('actinidiaceae', 'Gilg & Werderm.', 10, NULL, NULL, 'ericales'),
	('adelanthaceae', 'Grolle', 10, NULL, NULL, 'lophoziales'),
	('aextoxicaceae', 'Engl. & Gilg', 10, NULL, NULL, 'berberidopsidales'),
	('aizoaceae', 'Martinov', 10, NULL, NULL, 'caryophyllales'),
	('akaniaceae', 'Stapf', 10, NULL, NULL, 'brassicales'),
	('alismataceae', 'Vent.', 10, NULL, NULL, 'alismatales'),
	('alismatales', 'R.Br. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Monocots', 'magnoliidae'),
	('allisoniaceae', 'Schljakov', 10, NULL, NULL, 'fossombroniales'),
	('alseuosmiaceae', 'Airy Shaw', 10, NULL, NULL, 'asterales'),
	('alstroemeriaceae', 'Dumort.', 10, NULL, NULL, 'liliales'),
	('altingiaceae', 'Lindl.', 10, NULL, NULL, 'saxifragales'),
	('alzateaceae', 'S.A.Graham', 10, NULL, NULL, 'myrtales'),
	('amaranthaceae', 'Juss.', 10, NULL, NULL, 'caryophyllales'),
	('amaryllidaceae', 'J.St.-Hil.', 10, NULL, NULL, 'asparagales'),
	('amblystegiaceae', 'Kindb.', 10, NULL, NULL, 'hypnales'),
	('amborellaceae', 'Pichon', 10, NULL, NULL, 'amborellales'),
	('amborellales', 'Melikyan et al.', 8, 'Angiosperms', 'ANA Grade', 'magnoliidae'),
	('ambuchananiaceae', 'A.J.Shaw', 10, NULL, NULL, 'sphagnales'),
	('amphidiaceae', 'M.Stech', 10, NULL, NULL, 'amphidiales'),
	('amphidiales', 'D.Bell & Goffinet', 8, 'Bryophytes', NULL, 'dicranidae'),
	('anacampserotaceae', 'Eggli & Nyffeler', 10, NULL, NULL, 'caryophyllales'),
	('anacardiaceae', 'R.Br.', 10, NULL, NULL, 'sapindales'),
	('anastrophyllaceae', 'L.Söderstr., De Roo & Hedd.', 10, NULL, NULL, 'lophoziales'),
	('ancistrocladaceae', 'Planch. ex Walp.', 10, NULL, NULL, 'caryophyllales'),
	('andreaeaceae', 'Dumort.', 10, NULL, NULL, 'andreaeales'),
	('andreaeales', 'Limpr.', 8, 'Bryophytes', NULL, 'andreaeopsida'),
	('andreaeobryaceae', 'Steere', 10, NULL, NULL, 'andreaeobryales'),
	('andreaeobryales', 'B.M.Murray', 8, 'Bryophytes', NULL, 'andreaeobryopsida'),
	('andreaeobryopsida', 'Goffinet & W.R.Buck', 6, NULL, NULL, 'bryophyta'),
	('andreaeopsida', 'Trevis.', 6, NULL, NULL, 'bryophyta'),
	('anemiaceae', 'Link', 10, NULL, NULL, 'schizaeales'),
	('aneuraceae', 'H.Klinggr.', 10, NULL, NULL, 'metzgeriales'),
	('anisophylleaceae', 'Ridl.', 10, NULL, NULL, 'cucurbitales'),
	('annonaceae', 'Juss.', 10, NULL, NULL, 'magnoliales'),
	('anomodontaceae', 'Kindb.', 10, NULL, NULL, 'hypnales'),
	('antheliaceae', 'R.M.Schust.', 10, NULL, NULL, 'jungermanniales'),
	('anthocerotaceae', 'Dumort.', 10, NULL, NULL, 'anthocerotales'),
	('anthocerotales', 'Rabenh.', 8, 'Bryophytes', NULL, 'anthocerotidae'),
	('anthocerotidae', 'Engl.', 7, NULL, NULL, 'anthocerotopsida'),
	('anthocerotophyta', 'Stotler & Crand.-Stotl.', 3, NULL, NULL, 'bryobiotina'),
	('anthocerotopsida', 'Jancz.', 6, NULL, NULL, 'anthocerotophyta'),
	('antitrichiaceae', 'Ignatov & Ignatova', 10, NULL, NULL, 'hypnales'),
	('aongstroemiaceae', 'De Not.', 10, NULL, NULL, 'dicranales'),
	('aphanopetalaceae', 'Doweld', 10, NULL, NULL, 'saxifragales'),
	('aphloiaceae', 'Takht.', 10, NULL, NULL, 'crossosomatales'),
	('apiaceae', 'Lindl.', 10, NULL, NULL, 'apiales'),
	('apiales', 'Nakai', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('apocynaceae', 'Juss.', 10, NULL, NULL, 'gentianales'),
	('apodanthaceae', 'Tiegh. ex Takht.', 10, NULL, NULL, 'cucurbitales'),
	('aponogetonaceae', 'Planch.', 10, NULL, NULL, 'alismatales'),
	('aptandraceae', NULL, 10, NULL, NULL, 'santalales'),
	('aquifoliaceae', 'Bercht. & J.Presl', 10, NULL, NULL, 'aquifoliales'),
	('aquifoliales', 'Senft', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('araceae', 'Juss.', 10, NULL, NULL, 'alismatales'),
	('araliaceae', 'Juss.', 10, NULL, NULL, 'apiales'),
	('araucariaceae', 'Henkel & W.Hochst.', 10, NULL, NULL, 'araucariales'),
	('araucariales', 'Gorozh.', 8, 'Gymnosperms', NULL, 'cupressidae'),
	('archidiaceae', 'Schimp.', 10, NULL, NULL, 'archidiales'),
	('archidiales', 'Limpr.', 8, 'Bryophytes', NULL, 'dicranidae'),
	('arecaceae', 'Bercht. & J.Presl', 10, NULL, NULL, 'arecales'),
	('arecales', 'Bromhead', 8, 'Angiosperms', 'Monocots', 'magnoliidae'),
	('argophyllaceae', 'Takht.', 10, NULL, NULL, 'asterales'),
	('aristolochiaceae', 'Juss.', 10, NULL, NULL, 'piperales'),
	('arnelliaceae', 'Nakai', 10, NULL, NULL, 'jungermanniales'),
	('arthropteridaceae', 'Hong M.Liu, Hovenkamp & H.Schneid.', 10, NULL, NULL, 'polypodiineae'),
	('asparagaceae', 'Juss.', 10, NULL, NULL, 'asparagales'),
	('asparagales', 'Link', 8, 'Angiosperms', 'Monocots', 'magnoliidae'),
	('asphodelaceae', 'Juss.', 10, NULL, NULL, 'asparagales'),
	('aspleniaceae', 'Newman', 10, NULL, NULL, 'polypodiales'),
	('aspleniineae', 'H.Schneid. & C.J.Rothf.', 9, NULL, NULL, 'polypodiales'),
	('asteliaceae', 'Dumort.', 10, NULL, NULL, 'asparagales'),
	('asteraceae', 'Bercht. & J.Presl', 10, NULL, NULL, 'asterales'),
	('asterales', 'Link', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('asteropeiaceae', 'Takht. ex Reveal & Hoogland', 10, NULL, NULL, 'caryophyllales'),
	('atherospermataceae', 'R.Br.', 10, NULL, NULL, 'laurales'),
	('athyriaceae', 'Alston', 10, NULL, NULL, 'polypodiales'),
	('aulacomniaceae', 'Schimp.', 10, NULL, NULL, 'aulacomniales'),
	('aulacomniales', 'N.E.Bell, A.E.Newton & D.Quandt', 8, 'Bryophytes', NULL, 'bryidae'),
	('austrobaileyaceae', 'Croizat', 10, NULL, NULL, 'austrobaileyales'),
	('austrobaileyales', 'Takht. ex Reveal', 8, 'Angiosperms', 'ANA Grade', 'magnoliidae'),
	('aytoniaceae', 'Cavers', 10, NULL, NULL, 'marchantiales'),
	('balanopaceae', 'Benth. & Hook.f.', 10, NULL, NULL, 'malpighiales'),
	('balanophoraceae', 'Rich.', 10, NULL, NULL, 'santalales'),
	('balantiopsidaceae', 'Nakai', 10, NULL, NULL, 'jungermanniales'),
	('balsaminaceae', 'A.Rich.', 10, NULL, NULL, 'ericales'),
	('barbeuiaceae', 'Nakai', 10, NULL, NULL, 'caryophyllales'),
	('barbeyaceae', 'Rendle', 10, NULL, NULL, 'rosales'),
	('bartramiaceae', 'Schwägr.', 10, NULL, NULL, 'bartramiales'),
	('bartramiales', 'M.Menzel', 8, 'Bryophytes', NULL, 'bryidae'),
	('basellaceae', 'Raf.', 10, NULL, NULL, 'caryophyllales'),
	('bataceae', 'Mart. ex Perleb', 10, NULL, NULL, 'brassicales'),
	('begoniaceae', 'C.Agardh', 10, NULL, NULL, 'cucurbitales'),
	('berberidaceae', 'Juss.', 10, NULL, NULL, 'ranunculales'),
	('berberidopsidaceae', 'Takht.', 10, NULL, NULL, 'berberidopsidales'),
	('berberidopsidales', 'Doweld', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('betulaceae', 'Gray', 10, NULL, NULL, 'fagales'),
	('biebersteiniaceae', 'Schnizl.', 10, NULL, NULL, 'sapindales'),
	('bignoniaceae', 'Juss.', 10, NULL, NULL, 'lamiales'),
	('bixaceae', 'Kunth', 10, NULL, NULL, 'malvales'),
	('blandfordiaceae', 'R.Dahlgren & Clifford', 10, NULL, NULL, 'asparagales'),
	('blasiaceae', 'H.Klinggr.', 10, NULL, NULL, 'blasiales'),
	('blasiales', 'Stotler & Crand.-Stotl.', 8, 'Bryophytes', NULL, 'blasiidae'),
	('blasiidae', 'He-Nygrén, Juslén, Ahonen, Glenny & Piippo', 7, NULL, NULL, 'marchantiopsida'),
	('blechnaceae', 'Newman', 10, NULL, NULL, 'polypodiales'),
	('blepharidophyllaceae', 'R.M.Schust.', 10, NULL, NULL, 'jungermanniales'),
	('blepharostomataceae', 'W.Frey & M.Stech', 10, NULL, NULL, 'lepidoziales'),
	('bonnetiaceae', 'L.Beauvis. ex Nakai', 10, NULL, NULL, 'malpighiales'),
	('boraginaceae', 'Juss.', 10, NULL, NULL, 'boraginales'),
	('boraginales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('boryaceae', 'M.W.Chase et al.', 10, NULL, NULL, 'asparagales'),
	('brachytheciaceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('braithwaiteaceae', 'N.E.Bell, A.E.Newton & D.Quandt', 10, NULL, NULL, 'hypnodendrales'),
	('brassicaceae', 'Burnett', 10, NULL, NULL, 'brassicales'),
	('brassicales', 'Bromhead', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('brevianthaceae', 'J.J.Engel & R.M.Schust.', 10, NULL, NULL, 'lepidoziales'),
	('bromeliaceae', 'Juss.', 10, NULL, NULL, 'poales'),
	('bruchiaceae', 'Schimp.', 10, NULL, NULL, 'bruchiales'),
	('bruchiales', 'Goffinet', 8, 'Bryophytes', NULL, 'dicranidae'),
	('brunelliaceae', 'Engl.', 10, NULL, NULL, 'oxalidales'),
	('bruniaceae', 'R.Br. ex DC.', 10, NULL, NULL, 'bruniales'),
	('bruniales', 'Dumort.', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('bryaceae', 'Rchb.', 10, NULL, NULL, 'bryales'),
	('bryales', 'Limpr.', 8, 'Bryophytes', NULL, 'bryidae'),
	('bryidae', 'Engl.', 7, NULL, NULL, 'bryopsida'),
	('bryobiotina', 'Trevis.', 2, NULL, NULL, 'plantae'),
	('bryophyta', 'Schimp.', 3, NULL, NULL, 'bryobiotina'),
	('bryopsida', 'Ritgen', 6, NULL, NULL, 'bryophyta'),
	('bryowijkiaceae', 'M.Stech & W.Frey', 10, NULL, NULL, 'dicranales'),
	('bryoxiphiaceae', 'Besch.', 10, NULL, NULL, 'bryoxiphiales'),
	('bryoxiphiales', 'Á.Löve & D.Löve', 8, 'Bryophytes', NULL, 'dicranidae'),
	('burmanniaceae', 'Blume', 10, NULL, NULL, 'dioscoreales'),
	('burseraceae', 'Kunth', 10, NULL, NULL, 'sapindales'),
	('butomaceae', 'Mirb.', 10, NULL, NULL, 'alismatales'),
	('buxaceae', 'Dumort.', 10, NULL, NULL, 'buxales'),
	('buxales', 'Takht. ex Reveal', 8, 'Angiosperms', 'Basal Eudicots', 'magnoliidae'),
	('buxbaumiaceae', 'Schwägr.', 10, NULL, NULL, 'buxbaumiales'),
	('buxbaumiales', 'Cavers', 8, 'Bryophytes', NULL, 'buxbaumiidae'),
	('buxbaumiidae', 'Doweld', 7, NULL, NULL, 'bryopsida'),
	('byblidaceae', 'Domin', 10, NULL, NULL, 'lamiales'),
	('cabombaceae', 'Rich. ex A.Rich.', 10, NULL, NULL, 'nymphaeales'),
	('cactaceae', 'Juss.', 10, NULL, NULL, 'caryophyllales'),
	('calceolariaceae', 'Olmstead', 10, NULL, NULL, 'lamiales'),
	('callicladiaceae', 'Jan KuÄera & Ignatov', 10, NULL, NULL, 'hypnales'),
	('callicostaceae', 'H.A.Crum', 10, NULL, NULL, 'hookeriales'),
	('calliergonaceae', 'Vanderp., HedenÃ¤s, C.J.Cox & A.J.Shaw', 10, NULL, NULL, 'hypnales'),
	('calobryales', 'Hamlin', 8, 'Bryophytes', NULL, 'haplomitriidae'),
	('calomniaceae', 'Kindb.', 10, NULL, NULL, 'rhizogoniales'),
	('calophyllaceae', 'J.Agardh', 10, NULL, NULL, 'malpighiales'),
	('calycanthaceae', 'Lindl.', 10, NULL, NULL, 'laurales'),
	('calyceraceae', 'R.Br. ex Rich.', 10, NULL, NULL, 'asterales'),
	('calyculariaceae', 'He-NygrÃ©n, JuslÃ©n, Ahonen, Glenny & Piippo', 10, NULL, NULL, 'fossombroniales'),
	('calymperaceae', 'Kindb.', 10, NULL, NULL, 'dicranales'),
	('calypogeiaceae', 'Ordway', 10, NULL, NULL, 'jungermanniales'),
	('campanulaceae', 'Juss.', 10, NULL, NULL, 'asterales'),
	('campynemataceae', 'Dumort.', 10, NULL, NULL, 'liliales'),
	('canellaceae', 'Mart.', 10, NULL, NULL, 'canellales'),
	('canellales', 'Cronq.', 8, 'Angiosperms', 'Magnoliids', 'magnoliidae'),
	('cannabaceae', 'Martinov', 10, NULL, NULL, 'rosales'),
	('cannaceae', 'Juss.', 10, NULL, NULL, 'zingiberales'),
	('capparaceae', 'Juss.', 10, NULL, NULL, 'brassicales'),
	('caprifoliaceae', 'Juss.', 10, NULL, NULL, 'dipsacales'),
	('cardiopteridaceae', 'Blume', 10, NULL, NULL, 'aquifoliales'),
	('caricaceae', 'Dumort.', 10, NULL, NULL, 'brassicales'),
	('carlemanniaceae', 'Airy Shaw', 10, NULL, NULL, 'lamiales'),
	('caryocaraceae', 'Voigt', 10, NULL, NULL, 'malpighiales'),
	('caryophyllaceae', 'Juss.', 10, NULL, NULL, 'caryophyllales'),
	('caryophyllales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('casuarinaceae', 'R.Br.', 10, NULL, NULL, 'fagales'),
	('catagoniaceae', 'W.R.Buck & Ireland', 10, NULL, NULL, 'hypnales'),
	('catoscopiaceae', 'Boulay ex Broth.', 10, NULL, NULL, 'catoscopiales'),
	('catoscopiales', 'Ignatov & Ignatova', 8, 'Bryophytes', NULL, 'dicranidae'),
	('celastraceae', 'R.Br.', 10, NULL, NULL, 'celastrales'),
	('celastrales', 'Link', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('centroplacaceae', 'Doweld & Reveal', 10, NULL, NULL, 'malpighiales'),
	('cephalotaceae', 'Dumort.', 10, NULL, NULL, 'oxalidales'),
	('cephalotaxaceae', 'Neger', 10, NULL, NULL, 'cupressales'),
	('cephaloziaceae', 'Mig.', 10, NULL, NULL, 'lophoziales'),
	('cephaloziellaceae', 'Douin', 10, NULL, NULL, 'lophoziales'),
	('ceratodontaceae', 'Schimp.', 10, NULL, NULL, 'pottiales'),
	('ceratophyllaceae', 'Gray', 10, NULL, NULL, 'ceratophyllales'),
	('ceratophyllales', 'Link', 8, 'Angiosperms', 'Ceratophyllales', 'magnoliidae'),
	('cercidiphyllaceae', 'Engl.', 10, NULL, NULL, 'saxifragales'),
	('chloranthaceae', 'R.Br. ex Sims', 10, NULL, NULL, 'chloranthales'),
	('chloranthales', 'Mart.', 8, 'Angiosperms', 'Chloranthales', 'magnoliidae'),
	('chrysobalanaceae', 'R.Br.', 10, NULL, NULL, 'malpighiales'),
	('chrysoblastellaceae', 'Ignatov & Fedosov', 10, NULL, NULL, 'dicranales'),
	('cibotiaceae', 'Korall', 10, NULL, NULL, 'cyatheales'),
	('circaeasteraceae', 'Hutch.', 10, NULL, NULL, 'ranunculales'),
	('cistaceae', 'Juss.', 10, NULL, NULL, 'malvales'),
	('cleomaceae', 'Bercht. & J.Presl', 10, NULL, NULL, 'brassicales'),
	('clethraceae', 'Klotzsch', 10, NULL, NULL, 'ericales'),
	('cleveaceae', 'Cavers', 10, NULL, NULL, 'marchantiales'),
	('climaciaceae', 'Kindb.', 10, NULL, NULL, 'hypnales'),
	('clusiaceae', 'Lindl.', 10, NULL, NULL, 'malpighiales'),
	('codonaceae', 'Weigend & Hilger', 10, NULL, NULL, 'boraginales'),
	('colchicaceae', 'DC.', 10, NULL, NULL, 'liliales'),
	('columelliaceae', 'D.Don', 10, NULL, NULL, 'bruniales'),
	('combretaceae', 'R.Br.', 10, NULL, NULL, 'myrtales'),
	('commelinaceae', 'Mirb.', 10, NULL, NULL, 'commelinales'),
	('commelinales', 'Mirb. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Monocots', 'magnoliidae'),
	('connaraceae', 'R.Br.', 10, NULL, NULL, 'oxalidales'),
	('conocephalaceae', 'Müll.Frib. ex Grolle', 10, NULL, NULL, 'marchantiales'),
	('convolvulaceae', 'Juss.', 10, NULL, NULL, 'solanales'),
	('cordiaceae', 'R.Br. ex Dumort.', 10, NULL, NULL, 'boraginales'),
	('coriariaceae', 'DC.', 10, NULL, NULL, 'cucurbitales'),
	('cornaceae', 'Bercht. & J.Presl', 10, NULL, NULL, 'cornales'),
	('cornales', 'Link', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('corsiaceae', 'Becc.', 10, NULL, NULL, 'liliales'),
	('corsiniaceae', 'Ordway', 10, NULL, NULL, 'marchantiales'),
	('corynocarpaceae', 'Engl.', 10, NULL, NULL, 'cucurbitales'),
	('costaceae', 'Nakai', 10, NULL, NULL, 'zingiberales'),
	('coulaceae', NULL, 10, NULL, NULL, 'santalales'),
	('crassulaceae', 'J.St.-Hil.', 10, NULL, NULL, 'saxifragales'),
	('crossosomataceae', 'Engl.', 10, NULL, NULL, 'crossosomatales'),
	('crossosomatales', 'Takht. ex Reveal', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('cryphaeaceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('crypteroniaceae', 'A.DC.', 10, NULL, NULL, 'myrtales'),
	('ctenolophonaceae', 'Exell & Mendonça', 10, NULL, NULL, 'malpighiales'),
	('cucurbitaceae', 'Juss.', 10, NULL, NULL, 'cucurbitales'),
	('cucurbitales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('culcitaceae', 'Pic.Serm.', 10, NULL, NULL, 'cyatheales'),
	('cunoniaceae', 'R.Br.', 10, NULL, NULL, 'oxalidales'),
	('cupressaceae', 'Gray', 10, NULL, NULL, 'cupressales'),
	('cupressales', 'Link', 8, 'Gymnosperms', NULL, 'cupressidae'),
	('cupressidae', 'Doweld', 7, NULL, NULL, 'pinopsida'),
	('curtisiaceae', 'Takht.', 10, NULL, NULL, 'cornales'),
	('cyatheaceae', 'Kaulf.', 10, NULL, NULL, 'cyatheales'),
	('cyatheales', 'A.B.Frank', 8, 'Pteridophytes', NULL, 'polypodiidae'),
	('cyathodiaceae', 'Stotler & Crand.-Stotl.', 10, NULL, NULL, 'marchantiales'),
	('cycadaceae', 'Pers.', 10, NULL, NULL, 'cycadales'),
	('cycadales', 'Dumort.', 8, 'Gymnosperms', NULL, 'cycadidae'),
	('cycadidae', 'Pax', 7, NULL, NULL, 'cycadopsida'),
	('cycadophyta', 'Bessey', 3, NULL, NULL, 'pteridobiotina'),
	('cycadopsida', 'Brongn.', 6, NULL, NULL, 'cycadophyta'),
	('cyclanthaceae', 'Poit. ex A.Rich.', 10, NULL, NULL, 'pandanales'),
	('cymodoceaceae', 'Vines', 10, NULL, NULL, 'alismatales'),
	('cynomoriaceae', 'Endl. ex Lindl.', 10, NULL, NULL, 'saxifragales'),
	('cyperaceae', 'Juss.', 10, NULL, NULL, 'poales'),
	('cyrillaceae', 'Lindl.', 10, NULL, NULL, 'ericales'),
	('cystodiaceae', 'J.R.Croft', 10, NULL, NULL, 'polypodiales'),
	('cystopteridaceae', '(Payer) Shmakov', 10, NULL, NULL, 'polypodiales'),
	('cytinaceae', 'A.Rich.', 10, NULL, NULL, 'malvales'),
	('daltoniaceae', 'Schimp.', 10, NULL, NULL, 'hookeriales'),
	('daphniphyllaceae', 'Müll.Arg.', 10, NULL, NULL, 'saxifragales'),
	('dasypogonaceae', 'Dumort.', 10, NULL, NULL, 'arecales'),
	('datiscaceae', 'Dumort.', 10, NULL, NULL, 'cucurbitales'),
	('davalliaceae', 'M.R.Schomb. ex A.B.Frank', 10, NULL, NULL, 'polypodiales'),
	('degeneriaceae', 'I.W.Bailey & A.C.Sm.', 10, NULL, NULL, 'magnoliales'),
	('dendrocerotaceae', 'J.Haseg.', 10, NULL, NULL, 'dendrocerotales'),
	('dendrocerotales', 'T.Katag. & Furuki', 8, 'Bryophytes', NULL, 'dendrocerotidae'),
	('dendrocerotidae', 'R.J.Duff, J.C.Villarreal, Cargill & Renzaglia', 7, NULL, NULL, 'anthocerotopsida'),
	('dennstaedtiaceae', 'Lotsy', 10, NULL, NULL, 'polypodiales'),
	('dennstaedtiineae', 'Schwartsb. & Hovenkamp', 9, NULL, NULL, 'polypodiales'),
	('desmophlebiaceae', 'Mynssen, A.Vasco, Sylvestre, R.C.Moran & Rouhan', 10, NULL, NULL, 'aspleniineae'),
	('diapensiaceae', 'Lindl.', 10, NULL, NULL, 'ericales'),
	('dichapetalaceae', 'Baill.', 10, NULL, NULL, 'malpighiales'),
	('dicksoniaceae', 'M.R.Schomb.', 10, NULL, NULL, 'cyatheales'),
	('dicranaceae', 'Schimp.', 10, NULL, NULL, 'dicranales'),
	('dicranales', 'M.Fleisch.', 8, 'Bryophytes', NULL, 'dicranidae'),
	('dicranellaceae', 'M.Stech', 10, NULL, NULL, 'dicranales'),
	('dicranellopsidaceae', 'Bonfim Santos, Siebel & Fedosov', 10, NULL, NULL, 'dicranales'),
	('dicranidae', 'Doweld', 7, NULL, NULL, 'bryopsida'),
	('didiereaceae', 'Radlk.', 10, NULL, NULL, 'caryophyllales'),
	('didymochlaenaceae', 'Ching ex Li Bing Zhang & Liang Zhang', 10, NULL, NULL, 'polypodiineae'),
	('dilleniaceae', 'Salisb.', 10, NULL, NULL, 'dilleniales'),
	('dilleniales', 'DC. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('dioncophyllaceae', 'Airy Shaw', 10, NULL, NULL, 'caryophyllales'),
	('dioscoreaceae', 'R.Br.', 10, NULL, NULL, 'dioscoreales'),
	('dioscoreales', 'Mart.', 8, 'Angiosperms', 'Monocots', 'magnoliidae'),
	('dipentodontaceae', 'Merr.', 10, NULL, NULL, 'huerteales'),
	('diphysciaceae', 'M.Fleisch.', 10, NULL, NULL, 'diphysciales'),
	('diphysciales', 'M.Fleisch.', 8, 'Bryophytes', NULL, 'diphysciidae'),
	('diphysciidae', 'Ochyra', 7, NULL, NULL, 'bryopsida'),
	('diplaziopsidaceae', 'X.C.Zhang & Christenh.', 10, NULL, NULL, 'polypodiales'),
	('dipsacales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('dipteridaceae', 'Seward & E.Dale', 10, NULL, NULL, 'gleicheniales'),
	('dipterocarpaceae', 'Blume', 10, NULL, NULL, 'malvales'),
	('dirachmaceae', 'Hutch.', 10, NULL, NULL, 'rosales'),
	('disceliaceae', 'Schimp.', 10, NULL, NULL, 'disceliales'),
	('disceliales', 'Ignatov, Ignatova & Fedosov', 8, 'Bryophytes', NULL, 'funariidae'),
	('distichiaceae', 'Schimp.', 10, NULL, NULL, 'distichiales'),
	('distichiales', 'D.Bell & Goffinet', 8, 'Bryophytes', NULL, 'dicranidae'),
	('ditrichaceae', 'Limpr.', 10, NULL, NULL, 'pottiales'),
	('doryanthaceae', 'R.Dahlgren & Clifford', 10, NULL, NULL, 'asparagales'),
	('droseraceae', 'Salisb.', 10, NULL, NULL, 'caryophyllales'),
	('drosophyllaceae', 'Chrtek et al.', 10, NULL, NULL, 'caryophyllales'),
	('drummondiaceae', 'Goffinet', 10, NULL, NULL, 'scouleriales'),
	('dryopteridaceae', 'Herter', 10, NULL, NULL, 'polypodiales'),
	('dumortieraceae', 'D.G.Long', 10, NULL, NULL, 'marchantiales'),
	('ebenaceae', 'Gürke', 10, NULL, NULL, 'ericales'),
	('ecdeiocoleaceae', 'D.W.Cutler & Airy Shaw', 10, NULL, NULL, 'poales'),
	('echinodiaceae', 'Broth.', 10, NULL, NULL, 'hypnales'),
	('ehretiaceae', 'Mart.', 10, NULL, NULL, 'boraginales'),
	('elaeagnaceae', 'Juss.', 10, NULL, NULL, 'rosales'),
	('elaeocarpaceae', 'Juss.', 10, NULL, NULL, 'oxalidales'),
	('elatinaceae', 'Dumort.', 10, NULL, NULL, 'malpighiales'),
	('emblingiaceae', 'Airy Shaw', 10, NULL, NULL, 'brassicales'),
	('encalyptaceae', 'Schimp.', 10, NULL, NULL, 'encalyptales'),
	('encalyptales', 'Dixon', 8, 'Bryophytes', NULL, 'funariidae'),
	('endogemmaceae', 'Konstant., Vilnet & A.V.Troitsky', 10, NULL, NULL, 'jungermanniales'),
	('entodontaceae', 'Kindb.', 10, NULL, NULL, 'hypnales'),
	('ephedraceae', 'Dumort.', 10, NULL, NULL, 'ephedrales'),
	('ephedrales', 'Dumort.', 8, 'Gymnosperms', NULL, 'gnetidae'),
	('equisetaceae', 'Michx. ex DC.', 10, NULL, NULL, 'equisetales'),
	('equisetales', 'DC. ex Bercht. & J.Presl', 8, 'Pteridophytes', NULL, 'equisetidae'),
	('equisetidae', 'Warm.', 7, NULL, NULL, 'polypodiopsida'),
	('ericaceae', 'Juss.', 10, NULL, NULL, 'ericales'),
	('ericales', 'Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('eriocaulaceae', 'Martinov', 10, NULL, NULL, 'poales'),
	('erpodiaceae', 'Müll.Hal.', 10, NULL, NULL, 'erpodiales'),
	('erpodiales', 'Goffinet', 8, 'Bryophytes', NULL, 'dicranidae'),
	('erythropalaceae', NULL, 10, NULL, NULL, 'santalales'),
	('erythroxylaceae', 'Kunth', 10, NULL, NULL, 'malpighiales'),
	('escalloniaceae', 'R.Br. ex Dumort.', 10, NULL, NULL, 'escalloniales'),
	('escalloniales', 'Link', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('eucommiaceae', 'Engl.', 10, NULL, NULL, 'garryales'),
	('euphorbiaceae', 'Juss.', 10, NULL, NULL, 'malpighiales'),
	('euphroniaceae', 'Marc.-Berti', 10, NULL, NULL, 'malpighiales'),
	('eupomatiaceae', 'Orb.', 10, NULL, NULL, 'magnoliales'),
	('eupteleaceae', 'K.Wilh.', 10, NULL, NULL, 'ranunculales'),
	('eustichiaceae', 'Broth.', 10, NULL, NULL, 'eustichiales'),
	('eustichiales', 'Goffinet', 8, 'Bryophytes', NULL, 'dicranidae'),
	('fabaceae', 'Lindl.', 10, NULL, NULL, 'fabales'),
	('fabales', 'Bromhead', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('fabroniaceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('fagaceae', 'Dumort.', 10, NULL, NULL, 'fagales'),
	('fagales', 'Engl.', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('fissidentaceae', 'Schimp.', 10, NULL, NULL, 'dicranales'),
	('flagellariaceae', 'Dumort.', 10, NULL, NULL, 'poales'),
	('flatbergiaceae', 'A.J.Shaw', 10, NULL, NULL, 'sphagnales'),
	('flexitrichaceae', 'Ignatov & Fedosov ex D.Bell & Goffinet', 10, NULL, NULL, 'flexitrichales'),
	('flexitrichales', 'D.Bell & Goffinet', 8, 'Bryophytes', NULL, 'dicranidae'),
	('fontinalaceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('fossombroniaceae', 'Hazsl.', 10, NULL, NULL, 'fossombroniales'),
	('fossombroniales', 'Schljakov', 8, 'Bryophytes', NULL, 'pelliidae'),
	('fouquieriaceae', 'DC.', 10, NULL, NULL, 'ericales'),
	('francoaceae', 'A.Juss.', 10, NULL, NULL, 'geraniales'),
	('frankeniaceae', 'Desv.', 10, NULL, NULL, 'caryophyllales'),
	('frullaniaceae', 'Ordway', 10, NULL, NULL, 'frullaniales'),
	('frullaniales', 'D.Bell & D.G.Long', 8, 'Bryophytes', NULL, 'jungermanniidae'),
	('funariaceae', 'Schwägr.', 10, NULL, NULL, 'funariales'),
	('funariales', 'M.Fleisch.', 8, 'Bryophytes', NULL, 'funariidae'),
	('funariidae', 'Ochyra', 7, NULL, NULL, 'bryopsida'),
	('garryaceae', 'Lindl.', 10, NULL, NULL, 'garryales'),
	('garryales', 'Mart.', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('geissolomataceae', 'A.DC.', 10, NULL, NULL, 'crossosomatales'),
	('gelsemiaceae', 'L.Struwe & V.A.Albert', 10, NULL, NULL, 'gentianales'),
	('gentianaceae', 'Juss.', 10, NULL, NULL, 'gentianales'),
	('gentianales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('geocalycaceae', 'H.Klinggr.', 10, NULL, NULL, 'jungermanniales'),
	('geraniaceae', 'Juss.', 10, NULL, NULL, 'geraniales'),
	('geraniales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('gerrardinaceae', 'M.H.Alford', 10, NULL, NULL, 'huerteales'),
	('gesneriaceae', 'Rich. & Juss.', 10, NULL, NULL, 'lamiales'),
	('gigaspermaceae', 'A.Jaeger & Sauerb.', 10, NULL, NULL, 'gigaspermales'),
	('gigaspermales', 'Goffinet, Wickett, O.Werner, Ros, A.J.Shaw & C.J.Cox', 8, 'Bryophytes', NULL, 'gigaspermidae'),
	('gigaspermidae', 'M.Stech & W.Frey', 7, NULL, NULL, 'bryopsida'),
	('ginkgoaceae', 'Engl.', 10, NULL, NULL, 'ginkgoales'),
	('ginkgoales', 'Gorozh.', 8, 'Gymnosperms', NULL, 'ginkgoidae'),
	('ginkgoidae', 'Engl.', 7, NULL, NULL, 'ginkgoopsida'),
	('ginkgoopsida', 'Engl.', 6, NULL, NULL, 'ginkgophyta'),
	('ginkgophyta', 'Bessey', 3, NULL, NULL, 'pteridobiotina'),
	('gisekiaceae', 'Nakai', 10, NULL, NULL, 'caryophyllales'),
	('gleicheniaceae', 'C.Presl', 10, NULL, NULL, 'gleicheniales'),
	('gleicheniales', 'Link', 8, 'Pteridophytes', NULL, 'polypodiidae'),
	('gnetaceae', 'Blume', 10, NULL, NULL, 'gnetales'),
	('gnetales', 'Blume', 8, 'Gymnosperms', NULL, 'gnetidae'),
	('gnetidae', 'Pax', 7, NULL, NULL, 'pinopsida'),
	('goebeliellaceae', 'Verd.', 10, NULL, NULL, 'porellales'),
	('gomortegaceae', 'Reiche', 10, NULL, NULL, 'laurales'),
	('goodeniaceae', 'R.Br.', 10, NULL, NULL, 'asterales'),
	('goupiaceae', 'Miers', 10, NULL, NULL, 'malpighiales'),
	('greyiaceae', 'Hutch.', 10, NULL, NULL, 'geraniales'),
	('grimmiaceae', 'Arn.', 10, NULL, NULL, 'grimmiales'),
	('grimmiales', 'M.Fleisch.', 8, 'Bryophytes', NULL, 'dicranidae'),
	('griseliniaceae', 'Takht.', 10, NULL, NULL, 'apiales'),
	('grolleaceae', 'R.M.Schust.', 10, NULL, NULL, 'lepidoziales'),
	('grossulariaceae', 'DC.', 10, NULL, NULL, 'saxifragales'),
	('grubbiaceae', 'Endl. ex Meisn.', 10, NULL, NULL, 'cornales'),
	('guamatelaceae', 'S.H.Oh & D.Potter', 10, NULL, NULL, 'crossosomatales'),
	('gunneraceae', 'Meisn.', 10, NULL, NULL, 'gunnerales'),
	('gunnerales', 'Takht. ex Reveal', 8, 'Angiosperms', 'Basal Eudicots', 'magnoliidae'),
	('gymnomitriaceae', 'H.Klinggr.', 10, NULL, NULL, 'jungermanniales'),
	('gyrostemonaceae', 'A.Juss.', 10, NULL, NULL, 'brassicales'),
	('gyrothyraceae', 'R.M.Schust.', 10, NULL, NULL, 'jungermanniales'),
	('habrodontaceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('haemodoraceae', 'R.Br.', 10, NULL, NULL, 'commelinales'),
	('halophytaceae', 'S.Soriano', 10, NULL, NULL, 'caryophyllales'),
	('haloragaceae', 'R.Br.', 10, NULL, NULL, 'saxifragales'),
	('hamamelidaceae', 'R.Br.', 10, NULL, NULL, 'saxifragales'),
	('hanguanaceae', 'Airy Shaw', 10, NULL, NULL, 'commelinales'),
	('haplomitriaceae', 'Dědeček', 10, NULL, NULL, 'calobryales'),
	('haplomitriidae', 'Stotler & Crand.-Stotl.', 7, NULL, NULL, 'haplomitriopsida'),
	('haplomitriopsida', 'Stotler & Crand.-Stotl.', 6, NULL, NULL, 'marchantiophyta'),
	('hedwigiaceae', 'Schimp.', 10, NULL, NULL, 'hedwigiales'),
	('hedwigiales', 'Ochyra', 8, 'Bryophytes', NULL, 'bryidae'),
	('heliconiaceae', 'Vines', 10, NULL, NULL, 'zingiberales'),
	('helicophyllaceae', 'Broth.', 10, NULL, NULL, 'bartramiales'),
	('heliotropiaceae', 'Schrad.', 10, NULL, NULL, 'boraginales'),
	('helodiaceae', 'Ochyra', 10, NULL, NULL, 'hypnales'),
	('helwingiaceae', 'Decne.', 10, NULL, NULL, 'aquifoliales'),
	('hemidictyaceae', 'Christenh. & H.Schneid.', 10, NULL, NULL, 'polypodiales'),
	('herbertaceae', 'Müll.Frib. ex Fulford & Hatcher', 10, NULL, NULL, 'lepidoziales'),
	('hernandiaceae', 'Blume', 10, NULL, NULL, 'laurales'),
	('herzogianthaceae', 'Stotler & Crand.-Stotl.', 10, NULL, NULL, 'ptilidiales'),
	('herzogianthales', 'W.Sheng, Yang Liu bis & S.S.Dong', 8, NULL, NULL, 'jungermanniidae'),
	('heterocladiellaceae', 'Ignatov & Fedosov', 10, NULL, NULL, 'hypnales'),
	('himantandraceae', 'Diels', 10, NULL, NULL, 'magnoliales'),
	('hookeriaceae', 'Schimp.', 10, NULL, NULL, 'hookeriales'),
	('hookeriales', 'M.Fleisch.', 8, 'Bryophytes', NULL, 'bryidae'),
	('huaceae', 'A.Chev.', 10, NULL, NULL, 'oxalidales'),
	('huerteales', 'Doweld', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('humiriaceae', 'A.Juss.', 10, NULL, NULL, 'malpighiales'),
	('hydatellaceae', 'U.Hamann', 10, NULL, NULL, 'nymphaeales'),
	('hydrangeaceae', 'Dumort.', 10, NULL, NULL, 'cornales'),
	('hydrocharitaceae', 'Juss.', 10, NULL, NULL, 'alismatales'),
	('hydroleaceae', 'R.Br.', 10, NULL, NULL, 'solanales'),
	('hydrophyllaceae', 'R.Br.', 10, NULL, NULL, 'boraginales'),
	('hydropogonellaceae', 'B.H.Allen', 10, NULL, NULL, 'hypnales'),
	('hydrostachyaceae', 'Engl.', 10, NULL, NULL, 'cornales'),
	('hylocomiaceae', 'M.Fleisch.', 10, NULL, NULL, 'hypnales'),
	('hymenolomataceae', 'Ignatov & Fedosov', 10, NULL, NULL, 'scouleriales'),
	('hymenophyllaceae', 'Mart.', 10, NULL, NULL, 'hymenophyllales'),
	('hymenophyllales', 'A.B.Frank', 8, 'Pteridophytes', NULL, 'polypodiidae'),
	('hymenophytaceae', 'R.M.Schust.', 10, NULL, NULL, 'pallaviciniales'),
	('hypericaceae', 'Juss.', 10, NULL, NULL, 'malpighiales'),
	('hypnaceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('hypnales', 'W.R.Buck & Vitt', 8, 'Bryophytes', NULL, 'bryidae'),
	('hypnodendrales', 'N.E.Bell, A.E.Newton & D.Quandt', 8, 'Bryophytes', NULL, 'bryidae'),
	('hypodematiaceae', 'Ching', 10, NULL, NULL, 'polypodiales'),
	('hypodontiaceae', 'M.Stech', 10, NULL, NULL, 'dicranales'),
	('hypopterygiaceae', 'Mitt.', 10, NULL, NULL, 'hypopterygiales'),
	('hypopterygiales', 'Goffinet', 8, 'Bryophytes', NULL, 'bryidae'),
	('hypoxidaceae', 'R.Br.', 10, NULL, NULL, 'asparagales'),
	('icacinaceae', 'Miers', 10, NULL, NULL, 'icacinales'),
	('icacinales', 'Tiegh.', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('iridaceae', 'Juss.', 10, NULL, NULL, 'asparagales'),
	('irvingiaceae', 'Exell & Mendonça', 10, NULL, NULL, 'malpighiales'),
	('isoetaceae', 'Dumort.', 10, NULL, NULL, 'isoetales'),
	('isoetales', 'Prantl', 8, 'Pteridophytes', NULL, 'lycopodiopsida'),
	('iteaceae', 'J.Agardh', 10, NULL, NULL, 'saxifragales'),
	('ixioliriaceae', 'Nakai', 10, NULL, NULL, 'asparagales'),
	('ixonanthaceae', 'Planch. ex Miq.', 10, NULL, NULL, 'malpighiales'),
	('jocheniaceae', 'Jan KuÄera & Ignatov', 10, NULL, NULL, 'hypnales'),
	('joinvilleaceae', 'Toml. & A.C.Sm.', 10, NULL, NULL, 'poales'),
	('jubulaceae', 'H.Klinggr.', 10, NULL, NULL, 'jubulales'),
	('jubulales', 'Zodda', 8, 'Bryophytes', NULL, 'jungermanniidae'),
	('juglandaceae', 'DC. ex Perleb', 10, NULL, NULL, 'fagales'),
	('juncaceae', 'Juss.', 10, NULL, NULL, 'poales'),
	('juncaginaceae', 'Rich.', 10, NULL, NULL, 'alismatales'),
	('jungermanniales', 'H.Klinggr.', 8, 'Bryophytes', NULL, 'jungermanniidae'),
	('jungermanniidae', 'Engl.', 7, NULL, NULL, 'jungermanniopsida'),
	('jungermanniopsida', 'Stotler & Crand.-Stotl.', 6, NULL, NULL, 'marchantiophyta'),
	('kahakuloaceae', 'A.V.Freire, Judz., Cargill, L.L.Forrest & Gradst.', 10, NULL, NULL, 'fossombroniales'),
	('kewaceae', 'Christenh.', 10, NULL, NULL, 'caryophyllales'),
	('kirkiaceae', 'Takht.', 10, NULL, NULL, 'sapindales'),
	('koeberliniaceae', 'Engl.', 10, NULL, NULL, 'brassicales'),
	('krameriaceae', 'Dumort.', 10, NULL, NULL, 'zygophyllales'),
	('lacistemataceae', 'Mart.', 10, NULL, NULL, 'malpighiales'),
	('lamiaceae', 'Martinov', 10, NULL, NULL, 'lamiales'),
	('lamiales', 'Bromhead', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('lanariaceae', 'H.Huber ex R.Dahlgren', 10, NULL, NULL, 'asparagales'),
	('lardizabalaceae', 'R.Br.', 10, NULL, NULL, 'ranunculales'),
	('lauraceae', 'Juss.', 10, NULL, NULL, 'laurales'),
	('laurales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Magnoliids', 'magnoliidae'),
	('lecythidaceae', 'A.Rich.', 10, NULL, NULL, 'ericales'),
	('leiosporocerotaceae', 'Hässel ex Ochyra', 10, NULL, NULL, 'leiosporocerotales'),
	('leiosporocerotales', 'Hässel', 8, 'Bryophytes', NULL, 'leiosporocerotopsida'),
	('leiosporocerotopsida', 'Stotler & Crand.-Stotl.', 6, NULL, NULL, 'anthocerotophyta'),
	('lejeuneaceae', 'Rostovzev', 10, NULL, NULL, 'lejeuneales'),
	('lejeuneales', 'Bechteler, A.M.Sierra & D.G.Long', 8, 'Bryophytes', NULL, 'jungermanniidae'),
	('lembophyllaceae', 'Broth.', 10, NULL, NULL, 'hypnales'),
	('lentibulariaceae', 'Rich.', 10, NULL, NULL, 'lamiales'),
	('lepicoleaceae', 'R.M.Schust.', 10, NULL, NULL, 'lepidoziales'),
	('lepidobotryaceae', 'J.Léonard', 10, NULL, NULL, 'celastrales'),
	('lepidolaenaceae', 'Nakai', 10, NULL, NULL, 'porellales'),
	('lepidolaenales', 'Schljakov', 8, NULL, NULL, 'jungermanniidae'),
	('lepidoziaceae', 'Limpr.', 10, NULL, NULL, 'lepidoziales'),
	('lepidoziales', 'Schljakov', 8, 'Bryophytes', NULL, 'jungermanniidae'),
	('leptostomataceae', 'Schwägr.', 10, NULL, NULL, 'bryales'),
	('lepyrodontaceae', 'Broth.', 10, NULL, NULL, 'hypnales'),
	('leskeaceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('leucobryaceae', 'Schimp.', 10, NULL, NULL, 'archidiales'),
	('leucodontaceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('leucomiaceae', 'Broth.', 10, NULL, NULL, 'hookeriales'),
	('liliaceae', 'Juss.', 10, NULL, NULL, 'liliales'),
	('liliales', 'Perleb', 8, 'Angiosperms', 'Monocots', 'magnoliidae'),
	('limeaceae', 'Shipunov ex Reveal', 10, NULL, NULL, 'caryophyllales'),
	('limnanthaceae', 'R.Br.', 10, NULL, NULL, 'brassicales'),
	('linaceae', 'DC. ex Perleb', 10, NULL, NULL, 'malpighiales'),
	('linderniaceae', 'Borsch et al.', 10, NULL, NULL, 'lamiales'),
	('lindsaeaceae', 'M.R.Schomb.', 10, NULL, NULL, 'polypodiales'),
	('lindsaeineae', 'Lehtonen & Tuomisto', 9, NULL, NULL, 'polypodiales'),
	('loasaceae', 'Juss.', 10, NULL, NULL, 'cornales'),
	('loganiaceae', 'R.Br. ex Mart.', 10, NULL, NULL, 'gentianales'),
	('lomariopsidaceae', 'Alston', 10, NULL, NULL, 'polypodiales'),
	('lonchitidaceae', 'A.R.Sm. & M.Kessler', 10, NULL, NULL, 'polypodiales'),
	('lophiocarpaceae', 'Doweld & Reveal', 10, NULL, NULL, 'caryophyllales'),
	('lophocoleaceae', 'Müll.Frib. ex Vanden Berghen', 10, NULL, NULL, 'lepidoziales'),
	('lophopyxidaceae', 'H.Pfeiff.', 10, NULL, NULL, 'malpighiales'),
	('lophoziaceae', 'Cavers', 10, NULL, NULL, 'lophoziales'),
	('lophoziales', 'Schljakov', 8, 'Bryophytes', NULL, 'jungermanniidae'),
	('loranthaceae', 'Juss.', 10, NULL, NULL, 'santalales'),
	('lowiaceae', 'Ridl.', 10, NULL, NULL, 'zingiberales'),
	('loxsomataceae', 'C.Presl', 10, NULL, NULL, 'cyatheales'),
	('lunulariaceae', 'H.Klinggr.', 10, NULL, NULL, 'lunulariales'),
	('lunulariales', 'D.G.Long', 8, 'Bryophytes', NULL, 'marchantiidae'),
	('lycopodiaceae', 'P.Beauv. ex Mirb.', 10, NULL, NULL, 'lycopodiales'),
	('lycopodiales', 'DC. ex Bercht. & J.Presl', 8, 'Pteridophytes', NULL, 'lycopodiopsida'),
	('lycopodiophyta', 'D.H.Scott', 3, NULL, NULL, 'pteridobiotina'),
	('lycopodiopsida', 'Bartl.', 6, NULL, NULL, 'lycopodiophyta'),
	('lygodiaceae', 'M.Roem.', 10, NULL, NULL, 'schizaeales'),
	('lythraceae', 'J.St.-Hil.', 10, NULL, NULL, 'myrtales'),
	('macarthuriaceae', 'Christenh.', 10, NULL, NULL, 'caryophyllales'),
	('magnoliaceae', 'Juss.', 10, NULL, NULL, 'magnoliales'),
	('magnoliales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Magnoliids', 'magnoliidae'),
	('magnoliidae', 'Novák ex Takht.', 7, NULL, NULL, 'magnoliopsida'),
	('magnoliophyta', 'Cronquist, Takht. & W.Zimm. ex Reveal', 3, NULL, NULL, 'pteridobiotina'),
	('magnoliopsida', 'L.', 6, NULL, NULL, 'magnoliophyta'),
	('makinoaceae', 'Nakai', 10, NULL, NULL, 'fossombroniales'),
	('malpighiaceae', 'Juss.', 10, NULL, NULL, 'malpighiales'),
	('malpighiales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('malvaceae', 'Juss.', 10, NULL, NULL, 'malvales'),
	('malvales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('marantaceae', 'R.Br.', 10, NULL, NULL, 'zingiberales'),
	('marattiaceae', 'Kaulf.', 10, NULL, NULL, 'marattiales'),
	('marattiales', 'Link', 8, 'Pteridophytes', NULL, 'marattiidae'),
	('marattiidae', 'Klinge', 7, NULL, NULL, 'polypodiopsida'),
	('marcgraviaceae', 'Bercht. & J.Presl', 10, NULL, NULL, 'ericales'),
	('marchantiaceae', 'Chevall.', 10, NULL, NULL, 'marchantiales'),
	('marchantiales', 'Bercht. & J.Presl', 8, 'Bryophytes', NULL, 'marchantiidae'),
	('marchantiidae', 'Engl.', 7, NULL, NULL, 'marchantiopsida'),
	('marchantiophyta', 'Stotler & Crand.-Stotl.', 3, NULL, NULL, 'bryobiotina'),
	('marchantiopsida', 'Smyth & L.C.R.Smyth', 6, NULL, NULL, 'marchantiophyta'),
	('marsileaceae', 'Mirb.', 10, NULL, NULL, 'salviniales'),
	('martyniaceae', 'Horan.', 10, NULL, NULL, 'lamiales'),
	('mastigophoraceae', 'R.M.Schust.', 10, NULL, NULL, 'lepidoziales'),
	('matoniaceae', 'C.Presl', 10, NULL, NULL, 'gleicheniales'),
	('maundiaceae', 'Nakai', 10, NULL, NULL, 'alismatales'),
	('mayacaceae', 'Kunth', 10, NULL, NULL, 'poales'),
	('mazaceae', 'Reveal', 10, NULL, NULL, 'lamiales'),
	('meesiaceae', 'Schimp.', 10, NULL, NULL, 'splachnales'),
	('melanthiaceae', 'Batsch ex Borkh.', 10, NULL, NULL, 'liliales'),
	('melastomataceae', 'Juss.', 10, NULL, NULL, 'myrtales'),
	('meliaceae', 'Juss.', 10, NULL, NULL, 'sapindales'),
	('menispermaceae', 'Juss.', 10, NULL, NULL, 'ranunculales'),
	('menyanthaceae', 'Dumort.', 10, NULL, NULL, 'asterales'),
	('metaxyaceae', 'Pic.Serm.', 10, NULL, NULL, 'cyatheales'),
	('meteoriaceae', 'Kindb.', 10, NULL, NULL, 'hypnales'),
	('metteniusaceae', 'H.Karst. ex Schnizl.', 10, NULL, NULL, 'metteniusales'),
	('metteniusales', 'Takht.', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('metzgeriaceae', 'H.Klinggr.', 10, NULL, NULL, 'metzgeriales'),
	('metzgeriales', 'Rosenv.', 8, 'Bryophytes', NULL, 'metzgeriidae'),
	('metzgeriidae', 'Barthol.-Began', 7, NULL, NULL, 'jungermanniopsida'),
	('micromitriaceae', 'Smyth ex Goffinet & Budke', 10, NULL, NULL, 'archidiales'),
	('microteaceae', 'Schäferhoff & Borsch', 10, NULL, NULL, 'caryophyllales'),
	('microtheciellaceae', 'H.A.Mill. & A.J.Harr.', 10, NULL, NULL, 'hypnales'),
	('misodendraceae', 'J.Agardh', 10, NULL, NULL, 'santalales'),
	('mitrastemonaceae', 'Makino', 10, NULL, NULL, 'ericales'),
	('mitteniaceae', 'Broth.', 10, NULL, NULL, 'mitteniales'),
	('mitteniales', 'A.J.Shaw', 8, 'Bryophytes', NULL, 'dicranidae'),
	('miyabeaceae', 'Enroth, S.Olsson, Buchb., HedenÃ¤s, Huttunen & D.Quandt', 10, NULL, NULL, 'hypnales'),
	('mniaceae', 'Schwägr.', 10, NULL, NULL, 'bryales'),
	('moerckiaceae', 'K.I.Goebel ex Stotler & Crand.-Stotl.', 10, NULL, NULL, 'pallaviciniales'),
	('molluginaceae', 'Bartl.', 10, NULL, NULL, 'caryophyllales'),
	('monimiaceae', 'Juss.', 10, NULL, NULL, 'laurales'),
	('monocarpaceae', 'D.J.Carr ex Schelpe', 10, NULL, NULL, 'sphaerocarpales'),
	('monocleaceae', 'Horan.', 10, NULL, NULL, 'marchantiales'),
	('monosoleniaceae', 'Inoue', 10, NULL, NULL, 'marchantiales'),
	('montiaceae', 'Raf.', 10, NULL, NULL, 'caryophyllales'),
	('montiniaceae', 'Nakai', 10, NULL, NULL, 'solanales'),
	('moraceae', 'Gaudich.', 10, NULL, NULL, 'rosales'),
	('moringaceae', 'Martinov', 10, NULL, NULL, 'brassicales'),
	('muntingiaceae', 'C.Bayer et al.', 10, NULL, NULL, 'malvales'),
	('musaceae', 'Juss.', 10, NULL, NULL, 'zingiberales'),
	('myliaceae', 'Schljakov', 10, NULL, NULL, 'myliales'),
	('myliales', 'D.G.Long & D.Bell', 8, 'Bryophytes', NULL, 'jungermanniidae'),
	('myodocarpaceae', 'Doweld', 10, NULL, NULL, 'apiales'),
	('myricaceae', 'Rich. ex Kunth', 10, NULL, NULL, 'fagales'),
	('myriniaceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('myristicaceae', 'R.Br.', 10, NULL, NULL, 'magnoliales'),
	('myrothamnaceae', 'Nied.', 10, NULL, NULL, 'gunnerales'),
	('myrtaceae', 'Juss.', 10, NULL, NULL, 'myrtales'),
	('myrtales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('mystropetalaceae', NULL, 10, NULL, NULL, 'santalales'),
	('myuriaceae', 'Broth. ex M.Fleisch.', 10, NULL, NULL, 'hypnales'),
	('namaceae', 'Molinari', 10, NULL, NULL, 'boraginales'),
	('nartheciaceae', 'Fr. ex Bjurzon', 10, NULL, NULL, 'dioscoreales'),
	('neckeraceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('nelumbonaceae', 'A.Rich.', 10, NULL, NULL, 'proteales'),
	('neohodgsoniaceae', 'D.G.Long', 10, NULL, NULL, 'neohodgsoniales'),
	('neohodgsoniales', 'D.G.Long', 8, 'Bryophytes', NULL, 'marchantiidae'),
	('neotrichocoleaceae', 'Inoue', 10, NULL, NULL, 'ptilidiales'),
	('nepenthaceae', 'Dumort', 10, NULL, NULL, 'caryophyllales'),
	('nephrolepidaceae', 'Pic.Serm.', 10, NULL, NULL, 'polypodiales'),
	('neuradaceae', 'Kostel.', 10, NULL, NULL, 'malvales'),
	('nitrariaceae', 'Lindl.', 10, NULL, NULL, 'sapindales'),
	('noterocladaceae', 'W.Frey & M.Stech', 10, NULL, NULL, 'pelliales'),
	('nothofagaceae', 'Kuprian.', 10, NULL, NULL, 'fagales'),
	('notothyladaceae', 'Müll.Frib. ex Prosk.', 10, NULL, NULL, 'notothyladales'),
	('notothyladales', 'Hyvönen & Piippo', 8, 'Bryophytes', NULL, 'notothyladidae'),
	('notothyladidae', 'R.J.Duff, J.C.Villarreal, Cargill & Renzaglia', 7, NULL, NULL, 'anthocerotopsida'),
	('nyctaginaceae', 'Juss.', 10, NULL, NULL, 'caryophyllales'),
	('nymphaeaceae', 'Salisb.', 10, NULL, NULL, 'nymphaeales'),
	('nymphaeales', 'Salisb. ex Bercht. & J.Presl', 8, 'Angiosperms', 'ANA Grade', 'magnoliidae'),
	('nyssaceae', 'Juss. ex Dumort.', 10, NULL, NULL, 'cornales'),
	('obtusifoliaceae', 'Bakalin & Fedosov', 10, NULL, NULL, 'lophoziales'),
	('ochnaceae', 'DC.', 10, NULL, NULL, 'malpighiales'),
	('octoblepharaceae', 'A.Eddy ex M.Menzel', 10, NULL, NULL, 'dicranales'),
	('octoknemaceae', NULL, 10, NULL, NULL, 'santalales'),
	('oedipodiaceae', 'Schimp.', 10, NULL, NULL, 'oedipodiales'),
	('oedipodiales', 'Goffinet & W.R.Buck', 8, 'Bryophytes', NULL, 'polytrichopsida'),
	('olacaceae', 'R.Br.', 10, NULL, NULL, 'santalales'),
	('oleaceae', 'Hoffmanns. & Link', 10, NULL, NULL, 'lamiales'),
	('oleandraceae', 'Ching ex Pic.Serm.', 10, NULL, NULL, 'polypodiales'),
	('oleolophoziaceae', 'Bakalin & Fedosov', 10, NULL, NULL, 'lophoziales'),
	('onagraceae', 'Juss.', 10, NULL, NULL, 'myrtales'),
	('oncothecaceae', 'Kobuski ex Airy Shaw', 10, NULL, NULL, 'icacinales'),
	('onocleaceae', 'Pic.Serm.', 10, NULL, NULL, 'polypodiales'),
	('ophioglossaceae', 'Martinov', 10, NULL, NULL, 'ophioglossales'),
	('ophioglossales', 'Link', 8, 'Pteridophytes', NULL, 'ophioglossidae'),
	('ophioglossidae', 'Klinge', 7, NULL, NULL, 'polypodiopsida'),
	('opiliaceae', 'Valeton', 10, NULL, NULL, 'santalales'),
	('orchidaceae', 'Juss.', 10, NULL, NULL, 'asparagales'),
	('orobanchaceae', 'Vent.', 10, NULL, NULL, 'lamiales'),
	('orthodontiaceae', 'Goffinet', 10, NULL, NULL, 'orthodontiales'),
	('orthodontiales', 'N.E.Bell, A.E.Newton & D.Quandt', 8, 'Bryophytes', NULL, 'bryidae'),
	('orthorrhynchiaceae', 'S.H.Lin', 10, NULL, NULL, 'ptychomniales'),
	('orthostichellaceae', 'Enroth, Huttunen, Tangney, M.Stech & D.Quandt', 10, NULL, NULL, 'hypnales'),
	('orthotrichaceae', 'Arn.', 10, NULL, NULL, 'orthotrichales'),
	('orthotrichales', 'Dixon', 8, 'Bryophytes', NULL, 'bryidae'),
	('osmundaceae', 'Martinov', 10, NULL, NULL, 'osmundales'),
	('osmundales', 'Link', 8, 'Pteridophytes', NULL, 'polypodiidae'),
	('oxalidaceae', 'R.Br.', 10, NULL, NULL, 'oxalidales'),
	('oxalidales', 'Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('paeoniaceae', 'Raf.', 10, NULL, NULL, 'saxifragales'),
	('pallaviciniaceae', 'Mig.', 10, NULL, NULL, 'pallaviciniales'),
	('pallaviciniales', 'W.Frey & M.Stech', 8, 'Bryophytes', NULL, 'pelliidae'),
	('pandaceae', 'Engl. & Gilg', 10, NULL, NULL, 'malpighiales'),
	('pandanaceae', 'R.Br.', 10, NULL, NULL, 'pandanales'),
	('pandanales', 'R.Br. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Monocots', 'magnoliidae'),
	('papaveraceae', 'Juss.', 10, NULL, NULL, 'ranunculales'),
	('paracryphiaceae', 'Airy Shaw', 10, NULL, NULL, 'paracryphiales'),
	('paracryphiales', 'Takht. ex Reveal', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('passifloraceae', 'Juss. ex Roussel', 10, NULL, NULL, 'malpighiales'),
	('paulowniaceae', 'Nakai', 10, NULL, NULL, 'lamiales'),
	('pedaliaceae', 'R.Br.', 10, NULL, NULL, 'lamiales'),
	('pelliaceae', 'H.Klinggr.', 10, NULL, NULL, 'pelliales'),
	('pelliales', 'He-Nygrén, Juslén, Ahonen, Glenny & Piippo', 8, 'Bryophytes', NULL, 'pelliidae'),
	('pelliidae', 'Haeckel', 7, NULL, NULL, 'jungermanniopsida'),
	('peltantheraceae', 'Molinari', 10, NULL, NULL, 'lamiales'),
	('penaeaceae', 'Sweet ex Guill.', 10, NULL, NULL, 'myrtales'),
	('pennantiaceae', 'J.Agardh', 10, NULL, NULL, 'apiales'),
	('pentadiplandraceae', 'Hutch. & Dalziel', 10, NULL, NULL, 'brassicales'),
	('pentaphragmataceae', 'J.Agardh', 10, NULL, NULL, 'asterales'),
	('pentaphylacaceae', 'Engl.', 10, NULL, NULL, 'ericales'),
	('penthoraceae', 'Rydb. ex Britton', 10, NULL, NULL, 'saxifragales'),
	('peraceae', 'Klotzsch', 10, NULL, NULL, 'malpighiales'),
	('peridiscaceae', 'Kuhlm.', 10, NULL, NULL, 'saxifragales'),
	('perssoniellales', 'Schljakov', 8, 'Bryophytes', NULL, 'jungermanniidae'),
	('petalophyllaceae', 'Stotler & Crand.-Stotl.', 10, NULL, NULL, 'fossombroniales'),
	('petenaeaceae', 'Christenh.', 10, NULL, NULL, 'huerteales'),
	('petermanniaceae', 'Hutch.', 10, NULL, NULL, 'liliales'),
	('petiveriaceae', 'C.Agardh', 10, NULL, NULL, 'caryophyllales'),
	('petrosaviaceae', 'Hutch.', 10, NULL, NULL, 'petrosaviales'),
	('petrosaviales', 'Takht.', 8, 'Angiosperms', 'Monocots', 'magnoliidae'),
	('phellinaceae', 'Takht.', 10, NULL, NULL, 'asterales'),
	('philesiaceae', 'Dumort.', 10, NULL, NULL, 'liliales'),
	('philydraceae', 'Link', 10, NULL, NULL, 'commelinales'),
	('phrymaceae', 'Schauer', 10, NULL, NULL, 'lamiales'),
	('phyllanthaceae', 'Martinov', 10, NULL, NULL, 'malpighiales'),
	('phyllodrepaniaceae', 'Crosby', 10, NULL, NULL, 'bryales'),
	('phyllogoniaceae', 'Kindb.', 10, NULL, NULL, 'hypnales'),
	('phyllonomaceae', 'Small', 10, NULL, NULL, 'aquifoliales'),
	('phyllothalliaceae', 'E.A.Hodgs. ex T.Katag.', 10, NULL, NULL, 'pallaviciniales'),
	('phymatocerotaceae', 'R.J.Duff, J.C.Villarreal, Cargill & Renzaglia', 10, NULL, NULL, 'phymatocerotales'),
	('phymatocerotales', 'R.J.Duff, J.C.Villarreal, Cargill & Renzaglia', 8, 'Bryophytes', NULL, 'dendrocerotidae'),
	('physenaceae', 'Takht.', 10, NULL, NULL, 'caryophyllales'),
	('phytolaccaceae', 'R.Br.', 10, NULL, NULL, 'caryophyllales'),
	('picramniaceae', 'Fernando & Quinn', 10, NULL, NULL, 'picramniales'),
	('picramniales', 'Doweld', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('picrodendraceae', 'Small', 10, NULL, NULL, 'malpighiales'),
	('pinaceae', 'Spreng. ex Rudolphi', 10, NULL, NULL, 'pinales'),
	('pinales', 'Gorozh.', 8, 'Gymnosperms', NULL, 'pinidae'),
	('pinidae', 'Cronquist, Takht. & W.Zimm.', 7, NULL, NULL, 'pinopsida'),
	('pinophyta', 'Cronquist, Takht. & W.Zimm. ex Reveal', 3, NULL, NULL, 'pteridobiotina'),
	('pinopsida', 'Burnett', 6, NULL, NULL, 'pinophyta'),
	('piperaceae', 'Giseke', 10, NULL, NULL, 'piperales'),
	('piperales', 'Bercht. & J.Presl', 8, 'Angiosperms', 'Magnoliids', 'magnoliidae'),
	('pittosporaceae', 'R.Br.', 10, NULL, NULL, 'apiales'),
	('plagiochilaceae', 'Müll.Frib.', 10, NULL, NULL, 'lepidoziales'),
	('plagiogyriaceae', 'Bower', 10, NULL, NULL, 'cyatheales'),
	('plagiotheciaceae', 'M.Fleisch.', 10, NULL, NULL, 'hypnales'),
	('plantae', NULL, 1, NULL, NULL, NULL),
	('plantaginaceae', 'Juss.', 10, NULL, NULL, 'lamiales'),
	('platanaceae', 'T.Lestib.', 10, NULL, NULL, 'proteales'),
	('pleurophascaceae', 'Broth.', 10, NULL, NULL, 'pleurophascales'),
	('pleurophascales', 'Goffinet', 8, 'Bryophytes', NULL, 'dicranidae'),
	('pleuroziaceae', 'Müll.Frib.', 10, NULL, NULL, 'pleuroziales'),
	('pleuroziales', 'Schljakov', 8, 'Bryophytes', NULL, 'metzgeriidae'),
	('plocospermataceae', 'Hutch.', 10, NULL, NULL, 'lamiales'),
	('plumbaginaceae', 'Juss.', 10, NULL, NULL, 'caryophyllales'),
	('poaceae', 'Barnhart', 10, NULL, NULL, 'poales'),
	('poales', 'Small', 8, 'Angiosperms', 'Monocots', 'magnoliidae'),
	('podocarpaceae', 'Endl.', 10, NULL, NULL, 'araucariales'),
	('podostemaceae', 'Rich. ex Kunth', 10, NULL, NULL, 'malpighiales'),
	('polemoniaceae', 'Juss.', 10, NULL, NULL, 'ericales'),
	('polygalaceae', 'Hoffmanns. & Link', 10, NULL, NULL, 'fabales'),
	('polygonaceae', 'Juss.', 10, NULL, NULL, 'caryophyllales'),
	('polypodiaceae', 'J.Presl & C.Presl', 10, NULL, NULL, 'polypodiales'),
	('polypodiales', 'Link', 8, 'Pteridophytes', NULL, 'polypodiidae'),
	('polypodiidae', 'Cronquist, Takht. & W.Zimm.', 7, NULL, NULL, 'polypodiopsida'),
	('polypodiineae', 'Dumort.', 9, NULL, NULL, 'polypodiales'),
	('polypodiophyta', 'Cronquist, Takht. & Zimmerm.', 3, NULL, NULL, 'pteridobiotina'),
	('polypodiopsida', 'Cronquist, Takht. & W.Zimm.', 6, NULL, NULL, 'polypodiophyta'),
	('polytrichaceae', 'Schwägr.', 10, NULL, NULL, 'polytrichales'),
	('polytrichales', 'Cavers', 8, 'Bryophytes', NULL, 'polytrichopsida'),
	('polytrichopsida', 'Doweld', 6, NULL, NULL, 'bryophyta'),
	('pontederiaceae', 'Kunth', 10, NULL, NULL, 'commelinales'),
	('porellaceae', 'Cavers', 10, NULL, NULL, 'porellales'),
	('porellales', 'Schljakov', 8, 'Bryophytes', NULL, 'jungermanniidae'),
	('portulacaceae', 'Juss.', 10, NULL, NULL, 'caryophyllales'),
	('posidoniaceae', 'Vines', 10, NULL, NULL, 'alismatales'),
	('potamogetonaceae', 'Bercht. & J.Presl', 10, NULL, NULL, 'alismatales'),
	('pottiaceae', 'Hampe', 10, NULL, NULL, 'pottiales'),
	('pottiales', 'M.Fleisch.', 8, 'Bryophytes', NULL, 'dicranidae'),
	('primulaceae', 'Batsch ex Borkh.', 10, NULL, NULL, 'ericales'),
	('prionodontaceae', 'Broth.', 10, NULL, NULL, 'hypnales'),
	('proteaceae', 'Juss.', 10, NULL, NULL, 'proteales'),
	('proteales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Basal Eudicots', 'magnoliidae'),
	('pseudoditrichaceae', 'Steere & Z.Iwats.', 10, NULL, NULL, 'pseudoditrichales'),
	('pseudoditrichales', 'Ignatov & Fedosov', 8, 'Bryophytes', NULL, 'dicranidae'),
	('pseudolepicoleaceae', 'Fulford & J.Taylor', 10, NULL, NULL, 'lepidoziales'),
	('pseudoleskeaceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('pseudoleskeellaceae', 'Ignatov & Ignatova', 10, NULL, NULL, 'hypnales'),
	('pseudomoerckiaceae', 'Vilnet, Konstant., D.G.Long, N.D.Lockh. & Mamontov', 10, NULL, NULL, 'pallaviciniales'),
	('psilotaceae', 'J.W.Griff. & Henfr.', 10, NULL, NULL, 'psilotales'),
	('psilotales', 'Prantl', 8, 'Pteridophytes', NULL, 'ophioglossidae'),
	('pteridaceae', 'E.D.M.Kirchn.', 10, NULL, NULL, 'polypodiales'),
	('pteridineae', 'J.Prado & Schuettp.', 9, NULL, NULL, 'polypodiales'),
	('pteridobiotina', 'Britton & Brown', 2, NULL, NULL, 'plantae'),
	('pteridryaceae', 'Li Bing Zhang, X.M.Zhou, Liang Zhang & N.T.Lu', 10, NULL, NULL, 'polypodiineae'),
	('pterigynandraceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('pterobryaceae', 'Kindb.', 10, NULL, NULL, 'hypnales'),
	('pterobryellaceae', 'W.R.Buck & Vitt', 10, NULL, NULL, 'hypnodendrales'),
	('ptilidiaceae', 'H.Klinggr.', 10, NULL, NULL, 'ptilidiales'),
	('ptilidiales', 'Schljakov', 8, 'Bryophytes', NULL, 'jungermanniidae'),
	('ptychomitriaceae', 'Schimp.', 10, NULL, NULL, 'grimmiales'),
	('ptychomniaceae', 'M.Fleisch.', 10, NULL, NULL, 'ptychomniales'),
	('ptychomniales', 'W.R.Buck, C.J.Cox, A.J.Shaw & Goffinet', 8, 'Bryophytes', NULL, 'bryidae'),
	('pulchrinodaceae', 'D.Quandt, N.E.Bell & M.Stech', 10, NULL, NULL, 'bryales'),
	('putranjivaceae', 'Meisn.', 10, NULL, NULL, 'malpighiales'),
	('pylaisiaceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('pylaisiadelphaceae', 'Goffinet & W.R.Buck', 10, NULL, NULL, 'hypnales'),
	('quillajaceae', 'D.Don', 10, NULL, NULL, 'fabales'),
	('racopilaceae', 'Kindb.', 10, NULL, NULL, 'hypnodendrales'),
	('radulales', 'Stotler & Crand.-Stotl.', 8, 'Bryophytes', NULL, 'jungermanniidae'),
	('rafflesiaceae', 'Dumort.', 10, NULL, NULL, 'malpighiales'),
	('ranunculaceae', 'Juss.', 10, NULL, NULL, 'ranunculales'),
	('ranunculales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Basal Eudicots', 'magnoliidae'),
	('rapateaceae', 'Dumort.', 10, NULL, NULL, 'poales'),
	('regmatodontaceae', 'Broth.', 10, NULL, NULL, 'hypnales'),
	('resedaceae', 'Martinov', 10, NULL, NULL, 'brassicales'),
	('restionaceae', 'R.Br.', 10, NULL, NULL, 'poales'),
	('rhabdodendraceae', 'Prance', 10, NULL, NULL, 'caryophyllales'),
	('rhabdodontiaceae', 'Mishler, N.E.Bell & P.J.Dalton', 10, NULL, NULL, 'ptychomniales'),
	('rhabdoweisiaceae', 'Limpr.', 10, NULL, NULL, 'rhabdoweisiales'),
	('rhabdoweisiales', 'D.Bell & Goffinet', 8, 'Bryophytes', NULL, 'dicranidae'),
	('rhachidosoraceae', 'X.C.Zhang', 10, NULL, NULL, 'polypodiales'),
	('rhachitheciaceae', 'H.Rob.', 10, NULL, NULL, 'rhabdoweisiales'),
	('rhamnaceae', 'Juss.', 10, NULL, NULL, 'rosales'),
	('rhamphidiaceae', 'Fedosov, Brinda & Jan Kučera', 10, NULL, NULL, 'bruchiales'),
	('rhipogonaceae', 'Conran & Clifford', 10, NULL, NULL, 'liliales'),
	('rhizofabroniaceae', 'Huttunen, Ignatov, D.Quandt & HedenÃ¤s', 10, NULL, NULL, 'hypnales'),
	('rhizogemmaceae', 'Bonfim Santos, Siebel & Fedosov', 10, NULL, NULL, 'rhizogemmales'),
	('rhizogemmales', 'W.R.Buck & Goffinet', 8, NULL, NULL, 'dicranidae'),
	('rhizogoniaceae', 'Broth.', 10, NULL, NULL, 'rhizogoniales'),
	('rhizogoniales', 'Goffinet & W.R.Buck', 8, 'Bryophytes', NULL, 'bryidae'),
	('rhizophoraceae', 'Pers.', 10, NULL, NULL, 'malpighiales'),
	('rhytidiaceae', 'Broth.', 10, NULL, NULL, 'hypnales'),
	('ricciaceae', 'Rchb.', 10, NULL, NULL, 'marchantiales'),
	('riellaceae', 'Engl.', 10, NULL, NULL, 'sphaerocarpales'),
	('roellobryaceae', 'Ochyra', 10, NULL, NULL, 'bryales'),
	('roridulaceae', 'Martinov', 10, NULL, NULL, 'ericales'),
	('rosaceae', 'Juss.', 10, NULL, NULL, 'rosales'),
	('rosales', 'Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('rousseaceae', 'DC.', 10, NULL, NULL, 'asterales'),
	('rubiaceae', 'Juss.', 10, NULL, NULL, 'gentianales'),
	('ruficaulaceae', 'Bonfim Santos & Fedosov', 10, NULL, NULL, 'dicranales'),
	('ruppiaceae', 'Horan.', 10, NULL, NULL, 'alismatales'),
	('rutaceae', 'Juss.', 10, NULL, NULL, 'sapindales'),
	('rutenbergiaceae', 'M.Fleisch.', 10, NULL, NULL, 'hypnales'),
	('sabiaceae', 'Blume', 10, NULL, NULL, 'proteales'),
	('saccolomataceae', 'Doweld', 10, NULL, NULL, 'polypodiales'),
	('saccolomatineae', 'Hovenkamp', 9, NULL, NULL, 'polypodiales'),
	('saelaniaceae', 'Ignatov & Fedosov', 10, NULL, NULL, 'grimmiales'),
	('salicaceae', 'Mirb.', 10, NULL, NULL, 'malpighiales'),
	('salvadoraceae', 'Lindl.', 10, NULL, NULL, 'brassicales'),
	('salviniaceae', 'Martinov', 10, NULL, NULL, 'salviniales'),
	('salviniales', 'Link', 8, 'Pteridophytes', NULL, 'polypodiidae'),
	('sandeothallaceae', 'R.M.Schust.', 10, NULL, NULL, 'pallaviciniales'),
	('santalaceae', 'R.Br.', 10, NULL, NULL, 'santalales'),
	('santalales', 'R.Br. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('sapindaceae', 'Juss.', 10, NULL, NULL, 'sapindales'),
	('sapindales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('sapotaceae', 'Juss.', 10, NULL, NULL, 'ericales'),
	('sarcobataceae', 'Behnke', 10, NULL, NULL, 'caryophyllales'),
	('sarcolaenaceae', 'Caruel', 10, NULL, NULL, 'malvales'),
	('sarraceniaceae', 'Dumort.', 10, NULL, NULL, 'ericales'),
	('saulomataceae', 'W.R.Buck, C.J.Cox, A.J.Shaw & Goffinet', 10, NULL, NULL, 'hookeriales'),
	('saururaceae', 'Rich. ex T.Lestib.', 10, NULL, NULL, 'piperales'),
	('saxifragaceae', 'Juss.', 10, NULL, NULL, 'saxifragales'),
	('saxifragales', 'Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('scapaniaceae', 'Mig.', 10, NULL, NULL, 'lophoziales'),
	('scheuchzeriaceae', 'F.Rudolphi', 10, NULL, NULL, 'alismatales'),
	('schimperobryaceae', 'W.R.Buck, C.J.Cox, A.J.Shaw & Goffinet', 10, NULL, NULL, 'hookeriales'),
	('schisandraceae', 'Blume', 10, NULL, NULL, 'austrobaileyales'),
	('schistochilaceae', 'H.Buch', 10, NULL, NULL, 'perssoniellales'),
	('schistostegaceae', 'Schimp.', 10, NULL, NULL, 'dicranales'),
	('schizaeaceae', 'Kaulf.', 10, NULL, NULL, 'schizaeales'),
	('schizaeales', 'Schimp.', 8, 'Pteridophytes', NULL, 'polypodiidae'),
	('schlegeliaceae', 'Reveal', 10, NULL, NULL, 'lamiales'),
	('schoepfiaceae', 'Blume', 10, NULL, NULL, 'santalales'),
	('sciadopityaceae', 'Luerss.', 10, NULL, NULL, 'cupressales'),
	('scorpidiaceae', 'Ignatov & Ignatova', 10, NULL, NULL, 'hypnales'),
	('scouleriaceae', 'S.P.Churchill', 10, NULL, NULL, 'scouleriales'),
	('scouleriales', 'Goffinet & W.R.Buck', 8, 'Bryophytes', NULL, 'dicranidae'),
	('scrophulariaceae', 'Juss.', 10, NULL, NULL, 'lamiales'),
	('selaginellaceae', 'Willk.', 10, NULL, NULL, 'selaginellales'),
	('selaginellales', 'Prantl', 8, 'Pteridophytes', NULL, 'lycopodiopsida'),
	('seligeriaceae', 'Schimp.', 10, NULL, NULL, 'grimmiales'),
	('sematophyllaceae', 'Broth.', 10, NULL, NULL, 'hypnales'),
	('serpotortellaceae', 'W.D.Reese & R.H.Zander', 10, NULL, NULL, 'dicranales'),
	('setchellanthaceae', 'Iltis', 10, NULL, NULL, 'brassicales'),
	('simaroubaceae', 'DC.', 10, NULL, NULL, 'sapindales'),
	('simmondsiaceae', 'Tiegh.', 10, NULL, NULL, 'caryophyllales'),
	('siparunaceae', 'Schodde', 10, NULL, NULL, 'laurales'),
	('sladeniaceae', 'Airy Shaw', 10, NULL, NULL, 'ericales'),
	('smilacaceae', 'Vent.', 10, NULL, NULL, 'liliales'),
	('solanaceae', 'Juss.', 10, NULL, NULL, 'solanales'),
	('solanales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('sorapillaceae', 'M.Fleisch.', 10, NULL, NULL, 'sorapillales'),
	('sorapillales', 'Goffinet', 8, 'Bryophytes', NULL, 'dicranidae'),
	('sphaerocarpaceae', 'Heeg', 10, NULL, NULL, 'sphaerocarpales'),
	('sphaerocarpales', 'Cavers', 8, 'Bryophytes', NULL, 'marchantiidae'),
	('sphaerosepalaceae', 'Bullock', 10, NULL, NULL, 'malvales'),
	('sphagnaceae', 'Dumort.', 10, NULL, NULL, 'sphagnales'),
	('sphagnales', 'Limpr.', 8, 'Bryophytes', NULL, 'sphagnopsida'),
	('sphagnopsida', 'Schimp.', 6, NULL, NULL, 'bryophyta'),
	('sphenocleaceae', 'T.Baskerv.', 10, NULL, NULL, 'solanales'),
	('spiridentaceae', 'Broth.', 10, NULL, NULL, 'hypnodendrales'),
	('splachnaceae', 'Grev. & Arn.', 10, NULL, NULL, 'splachnales'),
	('splachnales', 'Ochyra', 8, 'Bryophytes', NULL, 'bryidae'),
	('stachyuraceae', 'J.Agardh', 10, NULL, NULL, 'crossosomatales'),
	('staphyleaceae', 'Martinov', 10, NULL, NULL, 'crossosomatales'),
	('stegnospermataceae', 'Nakai', 10, NULL, NULL, 'caryophyllales'),
	('stemonaceae', 'Caruel', 10, NULL, NULL, 'pandanales'),
	('stemonuraceae', 'Karehed', 10, NULL, NULL, 'aquifoliales'),
	('stereodontaceae', 'HedenÃ¤s, Schlesak & D.Quandt', 10, NULL, NULL, 'hypnales'),
	('stereophyllaceae', 'W.R.Buck & Ireland', 10, NULL, NULL, 'hypnales'),
	('stilbaceae', 'Kunth', 10, NULL, NULL, 'lamiales'),
	('strasburgeriaceae', 'Tiegh.', 10, NULL, NULL, 'crossosomatales'),
	('strelitziaceae', 'Hutch.', 10, NULL, NULL, 'zingiberales'),
	('strombosiaceae', NULL, 10, NULL, NULL, 'santalales'),
	('stylidiaceae', 'R.Br.', 10, NULL, NULL, 'asterales'),
	('styracaceae', 'DC. & Spreng.', 10, NULL, NULL, 'ericales'),
	('surianaceae', 'Arn.', 10, NULL, NULL, 'fabales'),
	('symphyodontaceae', 'M.Fleisch.', 10, NULL, NULL, 'hypnales'),
	('symplocaceae', 'Desf.', 10, NULL, NULL, 'ericales'),
	('taccaceae', 'Dumort.', 10, NULL, NULL, 'dioscoreales'),
	('takakiaceae', 'M.Stech & W.Frey', 10, NULL, NULL, 'takakiales'),
	('takakiales', 'S.Hatt. & Inoue ex R.M.Schust.', 8, 'Bryophytes', NULL, 'sphagnopsida'),
	('takakiopsida', 'Goffinet & W.R.Buck', 6, NULL, NULL, 'bryophyta'),
	('talinaceae', 'Doweld', 10, NULL, NULL, 'caryophyllales'),
	('tamaricaceae', 'Link', 10, NULL, NULL, 'caryophyllales'),
	('tapisciaceae', 'Takht.', 10, NULL, NULL, 'huerteales'),
	('taxaceae', 'Bercht. & J.Presl', 10, NULL, NULL, 'cupressales'),
	('taxiphyllaceae', 'Ignatov', 10, NULL, NULL, 'hypnales'),
	('tecophilaeaceae', 'Leyb.', 10, NULL, NULL, 'asparagales'),
	('tectariaceae', 'Panigrahi', 10, NULL, NULL, 'polypodiales'),
	('tetracarpaeaceae', 'Nakai', 10, NULL, NULL, 'saxifragales'),
	('tetrachondraceae', 'Wettst.', 10, NULL, NULL, 'lamiales'),
	('tetramelaceae', 'Airy Shaw', 10, NULL, NULL, 'cucurbitales'),
	('tetrameristaceae', 'Hutch.', 10, NULL, NULL, 'ericales'),
	('tetraphidaceae', 'Schimp.', 10, NULL, NULL, 'tetraphidales'),
	('tetraphidales', 'Cavers', 8, 'Bryophytes', NULL, 'polytrichopsida'),
	('theaceae', 'Mirb.', 10, NULL, NULL, 'ericales'),
	('theliaceae', 'M.Fleisch.', 10, NULL, NULL, 'hypnales'),
	('thelypteridaceae', 'Ching ex Pic.Serm.', 10, NULL, NULL, 'polypodiales'),
	('thismiaceae', 'J.Agardh', 10, NULL, NULL, 'dioscoreales'),
	('thomandersiaceae', 'Sreem.', 10, NULL, NULL, 'lamiales'),
	('thuidiaceae', 'Schimp.', 10, NULL, NULL, 'hypnales'),
	('thurniaceae', 'Engl.', 10, NULL, NULL, 'poales'),
	('thymelaeaceae', 'Juss.', 10, NULL, NULL, 'malvales'),
	('thyrsopteridaceae', 'C.Presl', 10, NULL, NULL, 'cyatheales'),
	('ticodendraceae', 'Gómez-Laur. & L.D.Gómez', 10, NULL, NULL, 'fagales'),
	('tiganophytaceae', 'Swanepoel, F.Forest & A.E.van Wyk', 10, NULL, NULL, 'brassicales'),
	('timmiaceae', 'Schimp.', 10, NULL, NULL, 'timmiales'),
	('timmiales', 'Ochyra', 8, 'Bryophytes', NULL, 'timmiidae'),
	('timmiellaceae', 'Y.Inoue & H.Tsubota', 10, NULL, NULL, 'distichiales'),
	('timmiidae', 'Ochyra', 7, NULL, NULL, 'bryopsida'),
	('tofieldiaceae', 'Takht.', 10, NULL, NULL, 'alismatales'),
	('torricelliaceae', 'Hu', 10, NULL, NULL, 'apiales'),
	('tovariaceae', 'Pax', 10, NULL, NULL, 'brassicales'),
	('trachylomataceae', 'W.R.Buck & Vitt', 10, NULL, NULL, 'hypnales'),
	('treubiaceae', 'Verd.', 10, NULL, NULL, 'treubiales'),
	('treubiales', 'Schljakov', 8, 'Bryophytes', NULL, 'treubiidae'),
	('treubiidae', 'Stotler & Crand.-Stotl.', 7, NULL, NULL, 'haplomitriopsida'),
	('trigoniaceae', 'A.Juss.', 10, NULL, NULL, 'malpighiales'),
	('trimeniaceae', 'Gibbs', 10, NULL, NULL, 'austrobaileyales'),
	('triuridaceae', 'Gardner', 10, NULL, NULL, 'pandanales'),
	('trochodendraceae', 'Eichler', 10, NULL, NULL, 'trochodendrales'),
	('trochodendrales', 'Takht. ex Cronq.', 8, 'Angiosperms', 'Basal Eudicots', 'magnoliidae'),
	('tropaeolaceae', 'Juss. ex DC.', 10, NULL, NULL, 'brassicales'),
	('typhaceae', 'Juss.', 10, NULL, NULL, 'poales'),
	('ulmaceae', 'Mirb.', 10, NULL, NULL, 'rosales'),
	('urticaceae', 'Juss.', 10, NULL, NULL, 'rosales'),
	('vahliaceae', 'Dandy', 10, NULL, NULL, 'vahliales'),
	('vahliales', 'Doweld', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('velloziaceae', 'J.Agardh', 10, NULL, NULL, 'pandanales'),
	('verbenaceae', 'J.St.Hil.', 10, NULL, NULL, 'lamiales'),
	('viburnaceae', 'Raf.', 10, NULL, NULL, 'dipsacales'),
	('violaceae', 'Batsch', 10, NULL, NULL, 'malpighiales'),
	('viridivelleraceae', 'I.G.Stone', 10, NULL, NULL, 'dicranales'),
	('vitaceae', 'Juss.', 10, NULL, NULL, 'vitales'),
	('vitales', 'Juss. ex Bercht. & J.Presl', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae'),
	('vochysiaceae', 'A.St.-Hil.', 10, NULL, NULL, 'myrtales'),
	('wellstediaceae', 'Novák', 10, NULL, NULL, 'boraginales'),
	('welwitschiaceae', 'Caruel', 10, NULL, NULL, 'welwitschiales'),
	('welwitschiales', 'Skottsb. ex Reveal', 8, 'Gymnosperms', NULL, 'gnetidae'),
	('wightiaceae', 'Bo Li, Bing Liu, Su Liu & Y.H.Tan', 10, NULL, NULL, 'lamiales'),
	('winteraceae', 'R.Br. ex Lindl.', 10, NULL, NULL, 'canellales'),
	('woodsiaceae', 'Herter', 10, NULL, NULL, 'polypodiales'),
	('xeronemataceae', 'M.W.Chase et al.', 10, NULL, NULL, 'asparagales'),
	('ximeniaceae', NULL, 10, NULL, NULL, 'santalales'),
	('xyridaceae', 'C.Agardh', 10, NULL, NULL, 'poales'),
	('zamiaceae', 'Horaninow', 10, NULL, NULL, 'cycadales'),
	('zingiberaceae', 'Martinov', 10, NULL, NULL, 'zingiberales'),
	('zingiberales', 'Griseb.', 8, 'Angiosperms', 'Monocots', 'magnoliidae'),
	('zosteraceae', 'Dumort.', 10, NULL, NULL, 'alismatales'),
	('zygophyllaceae', 'R.Br.', 10, NULL, NULL, 'zygophyllales'),
	('zygophyllales', 'Link', 8, 'Angiosperms', 'Core Eudicots', 'magnoliidae')
;
--add the root 
	INSERT INTO taxonomy.taxa_reference (id_taxonref, basename, authors, id_rank, id_parent, published, accepted) VALUES
	(1,'plantae',NULL,1,NULL,FALSE,TRUE)
;


--add constraints
	--on taxa_rank
	ALTER TABLE taxonomy.taxa_rank ADD CONSTRAINT taxa_rank_un UNIQUE (id_rank);
	ALTER TABLE taxonomy.taxa_rank ALTER COLUMN id_rank  SET NOT NULL;
	ALTER TABLE taxonomy.taxa_rank ALTER COLUMN rank_name  SET NOT NULL;
	--on taxa_reference
	ALTER TABLE taxonomy.taxa_reference ALTER COLUMN id_taxonref  SET NOT NULL;
	ALTER TABLE taxonomy.taxa_reference ALTER COLUMN basename SET NOT NULL;
	ALTER TABLE taxonomy.taxa_reference ALTER COLUMN id_rank SET NOT NULL;

	ALTER TABLE taxonomy.taxa_reference ALTER COLUMN accepted SET DEFAULT TRUE;
	ALTER TABLE taxonomy.taxa_reference ADD CONSTRAINT taxa_reference_pk PRIMARY KEY (id_taxonref);
	ALTER TABLE taxonomy.taxa_reference ADD CONSTRAINT taxa_reference_un UNIQUE (basename, id_parent);
	ALTER TABLE taxonomy.taxa_reference ADD CONSTRAINT id_parent_fk FOREIGN KEY (id_parent) REFERENCES taxonomy.taxa_reference(id_taxonref) ON UPDATE CASCADE ON DELETE CASCADE;
	ALTER TABLE taxonomy.taxa_reference ADD CONSTRAINT id_rank_fk FOREIGN KEY (id_rank) REFERENCES taxonomy.taxa_rank(id_rank);
	ALTER TABLE taxonomy.taxa_reference ADD CONSTRAINT check_name_length CHECK (id_rank <14 OR length(basename) >= 3);
	ALTER TABLE taxonomy.taxa_reference ADD CONSTRAINT check_name_null_parent CHECK (id_rank =1 OR id_parent IS NOT NULL);
	ALTER TABLE taxonomy.taxa_reference ADD CONSTRAINT check_name_self_parent CHECK (id_parent IS NULL OR id_parent <> id_taxonref);
	--on taxa_nameset
	ALTER TABLE taxonomy.taxa_nameset ALTER COLUMN name SET NOT NULL;
	ALTER TABLE taxonomy.taxa_nameset ALTER COLUMN category SET DEFAULT 5;
	ALTER TABLE taxonomy.taxa_nameset ADD CONSTRAINT check_category CHECK (category BETWEEN 0 AND 9);
	ALTER TABLE taxonomy.taxa_nameset ADD CONSTRAINT taxa_name_fk FOREIGN KEY (id_taxonref) REFERENCES taxonomy.taxa_reference(id_taxonref) ON UPDATE CASCADE ON DELETE CASCADE;
--add sequence
	CREATE SEQUENCE taxonomy.taxa_id_taxonref_seq OWNED BY taxonomy.taxa_reference.id_taxonref;
	SELECT SETVAL('taxonomy.taxa_id_taxonref_seq', COALESCE(MAX(id_taxonref), 0) + 1, false) FROM taxonomy.taxa_reference;
	ALTER TABLE taxonomy.taxa_reference ALTER COLUMN id_taxonref SET DEFAULT NEXTVAL('taxonomy.taxa_id_taxonref_seq');
--add indexes
	CREATE UNIQUE INDEX ux_basename_rank_partial ON taxonomy.taxa_reference (basename) WHERE id_rank < 21;
























